<a href="https://colab.research.google.com/github/sreekanth-ai/ML_content/blob/main/NUMPY_COMPLETE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY = Numerical Python

Advantages of numpy array:

1.Allows several Mathematical operations.

2.Faster operations.

In [ ]:
import numpy as np

list vs numpy - time taken to run the program.

In [ ]:
from time import process_time

In [ ]:
my_list = [i for i in range(10000)]

start_time = process_time()

my_list = [i+5 for i in my_list]

end_time = process_time()

print(end_time - start_time)


0.001324592999999874


Using numpy

In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0011577380000000748


NUMPY array

In [ ]:
list1 = np.array([1,3,5,6])
print(list1)
type(list1)

[1 3 5 6]


numpy.ndarray

In [ ]:
a = np.array([(1,5,67,7),(1,4,5,5)])
print(a)

[[ 1  5 67  7]
 [ 1  4  5  5]]


In [ ]:
a.shape

(2, 4)

In [ ]:
a.size

8

In [ ]:
c = np.array([(1,2.7,3),(4,5,6)],dtype=float)
print(c)

[[1.  2.7 3. ]
 [4.  5.  6. ]]


In [ ]:
y = np.zeros((4,5))
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
x = np.full((4,4),9)
print(x)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
a = np.ones((4,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
a = np.eye((4),dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
a = np.random.randint(10,100,(3,4))
print(a)

[[22 62 52 22]
 [23 80 90 38]
 [89 61 43 44]]


In [ ]:
a = np.random.random((3,4))
print(a)

[[0.39025176 0.85050648 0.79536486 0.49234787]
 [0.18678925 0.68351929 0.04237403 0.26246955]
 [0.20512679 0.03735318 0.20733934 0.44921874]]


arr of evenly spaced value -> specifing num of values

In [ ]:
a = np.linspace(10,30,6)
print(a)

[10. 14. 18. 22. 26. 30.]


In [ ]:
a = np.arange(10,30,6)
print(a)

[10 16 22 28]


converting the list into numpy

In [ ]:
list1 = [1,3,4,5,6,7]
type(list1)
np_arr = np.asarray(list1)
print(np_arr)
print(list1)
type(np_arr)

[1 3 4 5 6 7]
[1, 3, 4, 5, 6, 7]


numpy.ndarray

In [ ]:
c = np.random.randint(10,100,(5,7))
print(c)

[[14 48 98 26 65 94 48]
 [33 72 78 52 18 35 42]
 [40 69 77 23 53 50 84]
 [73 39 60 56 75 94 28]
 [81 95 60 50 65 81 65]]


In [ ]:
print(c.shape)

(5, 7)


In [ ]:
c.size

35

In [ ]:
c.ndim

2

In [ ]:
print(c.dtype)

int64


ADDING or concatination of two lists

In [ ]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


ARThimatic operation sum of two arrays in numpy

In [ ]:
a = np.random.randint(100,1000,(3,4))
c = np.random.randint(10,100,(3,4))
print(a)
print(c)
print(a+c)
# or print(np.add(a,c))

[[284 312 629 912]
 [161 896 954 573]
 [286 349 894 919]]
[[61 36 28 22]
 [76 53 42 92]
 [91 76 65 34]]
[[345 348 657 934]
 [237 949 996 665]
 [377 425 959 953]]


ARRAY MANUPULATION

In [ ]:
a = np.random.randint(1,10,(3,4))
print(a)
print(a.shape)
print(" ")
trans = np.transpose(a)
print(trans)
print(trans.shape)

[[6 8 9 1]
 [9 5 1 5]
 [5 4 7 4]]
(3, 4)
 
[[6 9 5]
 [8 5 4]
 [9 1 7]
 [1 5 4]]
(4, 3)


In [ ]:
tr = a.T
print(tr)
print(tr.shape)

[[6 9 5]
 [8 5 4]
 [9 1 7]
 [1 5 4]]
(4, 3)


ARRAY RESHAPING

In [ ]:
c = np.random.randint(10,100,(4,3))
print(c)
print(c.shape)
print("")
b = c.reshape(2,6)
print(b)
print(b.shape)

[[45 94 79]
 [85 72 34]
 [95 39 91]
 [43 57 15]]
(4, 3)

[[45 94 79 85 72 34]
 [95 39 91 43 57 15]]
(2, 6)


In [ ]:
l=[]
for i in range(1,5):
  x = int(input("enter:"))
  l.append(x)
print(l)
print(np.asarray(l))

enter:12
enter:23
enter:45
enter:7
[12, 23, 45, 7]
[12 23 45  7]


In [ ]:
x = np.array([1,2,3,4],ndmin = 2)
print(x)

[[1 2 3 4]]


In [ ]:
x = np.empty((2,3))
print(x)

[[1.  2.7 3. ]
 [4.  5.  6. ]]


In [ ]:
x = np.random.ranf(5)
print(x)

[0.73139009 0.28036868 0.33919969 0.90865788 0.12553331]


In [ ]:
x = np.random.randn(5)
print(x)

[-0.47755842 -0.98932831  2.15897618 -0.17498787 -0.19547814]


In [ ]:
x = np.array([1,2,3])
y = np.float32(x)
print(y)

[1. 2. 3.]


In [ ]:
z = np.reciprocal(x,dtype="f")
print(z)

[1.         0.5        0.33333334]
